version: '3.10.1'
services:
  cytoscape-desktop:
    image: cytoscape/cytoscape-desktop:3.10.1
    ports:
      - '${NOVNC_PORT}:${NOVNC_PORT}'
    environment:
      - XVFB_SCREEN_WIDTH=${NOVNC_SCREEN_WIDTH}
      - XVFB_SCREEN_HEIGHT=${NOVNC_SCREEN_HEIGHT}
      - NOVNC_PORT=${NOVNC_PORT}
      - CYREST_PORT=${CYREST_PORT}
  streamlit:
    image: kozo2/msdial2cytoscape:latest
    ports:
      - 8501:8501
